# Generated by Django 4.1.1 on 2022-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bilanz', models.FloatField()),
                ('gewinn', models.FloatField()),
                ('bic', models.CharField(max_length=11, primary_key=1, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
