# Generated by Django 4.1.1 on 2022-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0), ('overdraft__gte', 0), _connector='OR'), name='amount_overdraft_positive'),
        ),
    ]
