# Generated by Django 4.1.1 on 2022-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bic',
            field=models.CharField(default='MALADE51KRE', max_length=11, primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(default='MGB', max_length=30),
        ),
        migrations.AlterField(
            model_name='bank',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
