# Generated by Django 4.1.1 on 2022-09-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
