# Generated by Django 4.1.1 on 2022-09-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofdepositsaccount',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='creditcardaccount',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='transactionaccount',
            name='employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.employee'),
        ),
    ]
