# Generated by Django 4.1.1 on 2022-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cvv', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pin', models.IntegerField()),
                ('state', models.IntegerField()),
                ('expiration_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('interestrate', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('iban', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tan',
            fields=[
                ('tan', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_of_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('account', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAccount',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('interestrate', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('iban', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('overdraft', models.CharField(default=0, max_length=30)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bilanz',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='gewinn',
            new_name='profit',
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='TransactionAccountBankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transactionaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankstatement')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccountBankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.savingsaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankstatement')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('interestrate', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('cardnumber', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateOfDepositsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0)),
                ('interestrate', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('duration', models.IntegerField()),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='home.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankstatement')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='AccountBankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.savingsaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bankstatement')),
            ],
        ),
    ]
