# Generated by Django 4.1.1 on 2022-09-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagesgeldAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.account')),
                ('time_period', models.IntegerField(default=0)),
            ],
            bases=('home.account',),
        ),
        migrations.AlterField(
            model_name='account',
            name='negative_interest',
            field=models.FloatField(default=7.3),
        ),
    ]
