# Generated by Django 4.1.1 on 2022-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_amount_overdraft_positive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='amount_overdraft_positive',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('overdraft__gte', 0)), name='overdraft_positive'),
        ),
    ]
