# Generated by Django 4.1.1 on 2022-09-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tagesgeldaccount_time_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='negative_interest',
            field=models.FloatField(default=0.073),
        ),
    ]
