# Generated by Django 4.1.1 on 2022-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_account_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='period_of_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiving_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usage',
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
