# Generated by Django 4.1.1 on 2022-09-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tagesgeldaccount_alter_account_negative_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sending_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sending_account', to='home.account'),
        ),
    ]
