# Generated by Django 4.1.1 on 2022-09-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_transaction_period_of_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='period_of_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
