# Generated by Django 4.1.1 on 2022-09-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
