# Generated by Django 4.1.1 on 2022-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_transaction_period_of_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='period_of_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='standing_order_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
