# Generated by Django 4.1.1 on 2022-09-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_transaction_period_of_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='overdraft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.employee'),
        ),
    ]
